export {default as Category} from './category/Category';
export {default as Products} from './product/Products';
export {default as AddProduct} from './product/AddProduct';
export {default as EditProduct} from './product/EditProduct';
export {default as users} from './users/Users';
export {default as Home} from './home/Home';
export {default as Dashboard} from './dashboard/Dashboard';
export {default as PageNotFound} from './home/PageNotFound';
export {default as Customer} from './customer/Customer'
export {default as AddCust} from './customer/AddCust'
export {default as EditCust} from './customer/EditCust'
export {default as ShopPerformance} from './report/ShopPerformance'
export {default as LandingPage} from './landing/landing'