export {default as Category} from './category/Category';
export {default as Products} from './product/Products';
export {default as AddProduct} from './product/AddProduct';
export {default as EditProduct} from './product/EditProduct';
export {default as SettingProduct} from './product/SettingProduct'
export {default as users} from './users/Users';
export {default as Home} from './home/Home';
export {default as Cashier} from './cashier/Cashier'
export {default as Manual} from './manual/Manual'
export {default as Order} from './order/Order'
export {default as OrderWA} from './order/OrderWA'
export {default as PageNotFound} from './home/PageNotFound';
export {default as Customer} from './customer/Customer'
export {default as AddCust} from './customer/AddCust'
export {default as EditCust} from './customer/EditCust'
export {default as LandingPage} from './landing/landing'
export {default as HelpPage} from './settingsPage/Bantuan'
export {default as SettingPromoPoint} from './promopoint/SettingPromoPoint'
export {default as SettingShop} from './shop/SettingShop'
export {default as SettingOrderOnline} from './onlineorder/SettingOrderOnline'
export {default as Courier} from './onlineorder/Courier'
export {default as OnlinePayment} from './onlineorder/OnlinePayment'
export {default as Inbox} from './inbox/Inbox'
export {default as ProfitNLoss} from './report/ProfitNLoss'
export {default as CashFlow} from './report/CashFlow'
export {default as BalanceSheet} from './report/BalanceSheet'
export {default as Printer} from './printreceipt/Printer'
export {default as Receipt} from './printreceipt/Receipt'
