export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCEED = 'GET_CATEGORY_SUCCEED';
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCEEDED = 'CREATE_CATEGORY_SUCCEEDED';

export const FIND_CATEGORY = 'FIND_CATEGORY';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCEEDED = 'UPDATE_CATEGORY_SUCCEEDED';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCEEDED = 'DELETE_CATEGORY_SUCCEEDED';

