export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCEED = 'GET_PRODUCT_SUCCEED';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCEED = 'ADD_PRODUCT_SUCCEED';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCEED = 'UPDATE_PRODUCT_SUCCEED';

export const NEXT_PAGE = 'NEXT_PAGE';